name: CMake_Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Build a Function library gcc
      run: |
        cmake -H. -B_build -DCMAKE_C_COMPILER=gcc
        cmake --build _build
      shell: bash
      working-directory: Function_lib

    - name: Build a databaze application gcc
      run: |
        cmake -H. -B_build -DCMAKE_C_COMPILER=gcc
        cmake --build _build
      shell: bash
      working-directory: databaze
    
